### ISSUE TITLE
make clear tools/process for creating the WARCs

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/harvesting-toolkit#3]
based on conversation from @b5

**Comment by b5** [comment]
added a warc-generator in /tools. Turns out good old wget can generate warcs without a problem. I've updated the docs to reflect the gzip compression added by wget. We should probably chat about weather to download the gzipped version, but I think its a good idea to use it. There's a good chance it'll provide parity with other tools.

**Comment by dcwalk** [comment]
When we've tried to test warcs generated via `wget` they were failing to validate/open. Are the ones you are generating playable using the web archive viewer? (https://github.com/ikreymer/webarchiveplayer)

Could we add in a step to validate or test the warcs? from [an issue](https://github.com/edgi-govdata-archiving/eis-WARC-archiver/issues/4) in another repo:

> The only two tools I'm aware of for checking warcs in python are:
>   **IA's warc** https://github.com/internetarchive/warc (and https://warc.readthedocs.io/en/latest/)
>   **warcat** https://github.com/chfoo/warcat/tree/master/warcat

**Comment by dcwalk** [comment]
Related to my comment in #4 , I think we need ensure we are generating warcs that are comparable to Internet Archive versions. It looks like right now we are not just using wget.

**Comment by b5** [comment]
Okay, I've finally had a proper chance to sit down & understand what's going on with this .warc file stuff, and it seems there's been some confusion of purpose.

I had intended for the .warc copy of the page in this version to be a an html-only (no linked content) copy of the site so we could programmatically look for any missed links later on. By design the warc file was not to include any of the linked assets (in the example case xls & zip files), as those were what the harvester is attempting to parse from the page & download into the /data directory. This is the "bagged" approach that we'd been using at Data Rescue Philly, and overlaps the "complete-warc-archive" approach.

If I understand correctly, the https://github.com/edgi-govdata-archiving/eis-WARC-archiver repo is building completely reproducible copies of pages, linked assets included. This seems like the ideal solution. I'm guessing the general issue is it's just tough to use?

If so, I'd recommend we use the wget --warc option for this toolkit & add indications to the documentation that this is a "light" .warc (as opposed to a "full" warc), and this toolkit would remain useful only until we can get an easier version of the "full" warc archiver up & running in an easier to use package.

**Comment by dcwalk** [comment]
To ensure I'm following, by harvester you mean your [wget-loop](https://github.com/edgi-govdata-archiving/harvesting-toolkit/tree/master/tools/wget-loop) tool? Or a person as a harvester?

So the intent for these warcs is _just_ to refer back to for missed links? There is no preservation component?  

If that is a case is warc the correct format? We've had a lot of confusion around preservation and fidelity and I'm nervous to use a preservation format if we know we are not generating an appropriate one.

Can you sketch out a workflow in terms of how warcs would be used to verify missing links? We're finding the toolchain for working with warcs less than straightforward for people without a preservation background.

**Comment by b5** [comment]
Apologies, I meant "harvester" as a person :)

The general flow for checking for missing links would be something like:

1. assemble directory of these finalized "bags"
2. have a script iterate through each bag, loading the .html file from the warc into an html parser
3. have the parser strip out all links, iterate through each link & cross-check endpoints against the list of downloaded files.
4. what's left is (theoretically) a list of all the links that *weren't* downloaded.

The purpose of having a copy of the html, however, goes a bit beyond checking for links. I'm imagining a situation where we'd need to cross-reference between a separate .warc capture from somewhere else, and the files harvested here. In that case, having a copy of the html in each location may prove useful, as we can start to do comparison between the two files to confirm / deny it's the same page.

I very much like your point about not using a warc for this. Maybe we use standard wget, and we could change the instructions to being a regular .html file? It help simplify the toolkit, and I'm a big fan of simple :)

**Comment by dcwalk** [comment]
Ah okay, makes sense!
Yeah, generating html files as an more of an audit record for checking missing links sounds good to me 👍

**Comment by b5** [comment]
ooooh "audit record", now _that's_ a great term. I'll update the repo

**Comment by dcwalk** [comment]
Moving away from warcs at the format for now, marking this as won't fix and closing.
